apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myprofile
  namespace: myprofile
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: myprofile
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
